### ISSUE TITLE
Response to #15

### ISSUE THREAD

**Issue by wootwoot1234** [bugsnag/bugsnag-sourcemaps#16]
I can't comment on any of the bugsnag repositories on github, I don't know why.  I can create issues but not reply.  So I have to create a new issue every time I want to say something, sorry.  Not sure if it's my settings, your settings or github but I don't have this issue on any other repositories and I'm pretty active on github.

In response to issue #15:

Nevermind.  Found examples here: https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/

cheers!

**Comment by bengourley** [comment]
Hi @wootwoot1234, unfortunately some aggressive ad blocker/tracking prevention browser extensions block Bugsnag and this affects our Github issues too, since the regex is particularly loosely defined. We're figuring out the best way to deal with this but for the moment disabling your ad blocker on github.com/bugsnag.com should sort it!

**Comment by wootwoot1234** [comment]
I see, it was on my end, it seems like it always is.  Doh!

If you're reading this, the fix worked.

Thanks!
