### ISSUE TITLE
[Feature]- Delete all source Maps option before uploading new ones

### ISSUE THREAD

**Issue by sirajtahrawashmen** [bugsnag/bugsnag-sourcemaps#50]
### Expected behavior
In case source Maps contain hashes, and on each build a new file with a new hash is being generated, so I need to delete all previous files

### Additional information
I am using Create-react-app which generates [name].[hash].js.[map] with #hash being generated each time the file changes, so I can't really override them as I don't know what the hash is. Having the option to clear all uploaded source Maps before updating new ones would be a great feature to have

**Comment by snmaynard** [comment]
@sirajtahrawashmen why do you need to delete them at all? We match on the URL so the hash changing means we would match a different source map - so it should work as is AFAIK.

**Comment by sirajtahrawashmen** [comment]
yes that is correct, however the issue is not with the new files being uploaded, but the old files staying there. the `overwrite` option overwrite the files if they have the same name. but in case the old file is `example.[hash].js.map` and the new file is `example.[new-hash].js.map`, the new file gets uploaded without overwriting the old one. that's why having a way to delete all sourceMaps would make sure only the new files are uploaded

**Comment by mattdyoung** [comment]
Hi @sirajtahrawashmen 

The old files staying there is by design. This is to allow support for applying source maps to multiple versions of your code at the same time. E.g. you might deploy a new version to a staging environment (and upload new source maps for that version) but you'd still need the source maps for the previous version to remain so that they continue to be applied to your production errors.

The source maps are applied to your incoming error reports by matching the URL (and the app version if you've specified one):
https://docs.bugsnag.com/api/js-source-map-upload/#why-isn-39-t-the-uploaded-source-map-getting-applied-to-my-error

So the existence of previous versions of uploaded source maps in Bugsnag won't impact your new source maps successfully being applied to errors from your new version.

**Comment by anikolaev** [comment]
Here is the scenario when it could be useful. There are several stages (production, staging, demo) but 'demo' rebuilds and deploys automatically on each commit. There is a git hash commit in `appVersion` ('demo-123...'). So old source map files are absolutely useless after each commit to demo. The problem is they couldn't be easily deleted. You need to delete them one by one because if you delete all source maps at once you also delete staging and production versions. Maybe we should change appVersion to demo-latest and send git hash in meta info. In this case grouping of errors will not work though.

**Comment by xljones** [comment]
Hey @anikolaev, with your use case you can indeed just keep uploading new maps with the new source URLs and App Versions, it's no problem. The old maps just won't get used.

As a side-note; there's also an inherent risk that a user may accidentally delete maps which they did not intend to, so minimizing this risk from our perspective is worthwhile. For this reason, I don't expect to see any changes on this unless there's a significant benefit to doing so.
